# check interval
interval_secs = 10

# percentage to notify about low battery
low_pct = 15

# percentage to notify and sleep
sleep_pct = 0

# the sleep command
sleep_command = "systemctl suspend"

# warn when discharging and connected to monitors; 0 to turn off
warn_on_mons_with_no_ac = 0

# warn for bluetooth devices; 0 to turn off
bluetooth_low_pct = 0
