# <monitors />
# wiki https://wiki.hyprland.org/Configuring/Monitors/
monitor=eDP-1,preferred,0x0,1
monitor=,preferred,auto,1

exec-once = libinput-gestures-setup restart
exec-once = ydotoold

input {
	sensitivity = 0.7
}
