# preload = ~/.config/wallpaper/wallpaper.png
# preload = ~/.config/wallpaper/new-formula.png
# preload = ~/.config/wallpaper/train.png
# preload = ~/.config/wallpaper/vhs.png

# wallpaper = ,~/.config/wallpaper/new-formula-white.png
wallpaper {
	monitor =
	path = ~/.config/wallpaper/train.png
}

splash = false
