# <windowrule v2 />
# wiki https://wiki.hyprland.org/Configuring/Window-Rules/#window-rules-v2

windowrule {
	name = center
	center = on
	match:class = .
}

# <opacity />
windowrule {
	name = windowrule-1
	opacity = 0.8 0.8
	float = on
	match:class = ^(7zFM|7zfm)$
}

windowrule {
	name = windowrule-2
	opacity = 0.8 0.8
	float = on
	match:class = ^(blueman-manager)$
}

windowrule {
	name = windowrule-3
	opacity = 0.8 0.8
	float = on
	match:class = ^(chromium)$
	match:title = ^(Save File|Open File|Open Files)$
}

windowrule {
	name = windowrule-4
	opacity = 0.8 0.8
	float = on
	match:class = ^(com.nextcloud.desktopclient.nextcloud)$
}

windowrule {
	name = windowrule-5
	opacity = 0.8 0.8
	float = on
	match:class = ^(pavucontrol)$
}

windowrule {
	name = windowrule-6
	opacity = 0.8 0.8
	match:class = ^(Steam|steam)$
}

windowrule {
	name = windowrule-7
	opacity = 0.8 0.8
	float = on
	match:class = ^(thunar|Thunar)$
}

windowrule {
	name = windowrule-8
	opacity = 0.8 0.8
	float = on
	size = 1000 700
	match:class = ^(org.gnome.Nautilus)$
}

windowrule {
	name = windowrule-9
	opacity = 0.8 0.8
	float = on
	match:class = ^(com.system76.CosmicFiles)$
}

windowrule {
	name = windowrule-10
	opacity = 0.8 0.8
	float = on
	move = 695 1335
	match:class = ^(net.sapples.LiveCaptions)$
}

windowrule {
	name = windowrule-11
	opacity = 0.8 0.8
	float = on
	match:class = ^(chrome-nngceckbapebfimnlniiiahkandclblb-Default)$
}

# <float />
windowrule {
	name = windowrule-12
	float = on
	match:class = ^(Steam|steam|Steam setup)$
}

# <size />
windowrule {
	name = windowrule-13
	size = 1000 700
	match:class = ^(thunar|Thunar)$
	match:title = .*- Thunar$
}

# <temp />
windowrule {
	name = windowrule-14
	float = on
	match:class = LibreWolf
	match:title = negative:.*LibreWolf.*
}

windowrule {
	name = windowrule-15
	float = on
	match:class = LibreWolf
	match:title = Extension:.*
}

windowrule {
	name = windowrule-16
	move = 1400 975
	size = 750 420
	match:class = LibreWolf
	match:title = Picture-in-Picture
}
