theme = "fix_solarized_light"

[editor]
completion-trigger-len = 1
default-yank-register = "+"
end-of-line-diagnostics = "hint"
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.soft-wrap]
enable = true

[keys.normal]
# unbind the arrow keys so i get used to vim movement
right = "no_op"
left = "no_op"
down = "no_op"
up = "no_op"
K = "hover"
# save
z = ":w"
# start and end of line
"$" = "goto_line_end"
"0" = "goto_first_nonwhitespace"
# refactor
F2 = "rename_symbol"
# selection
"+" = "flip_selections"
w = "@emiw"
# tmp
Q = "no_op"

[keys.normal.q]
q = "file_picker_in_current_directory"
o = "symbol_picker"
t = "workspace_symbol_picker"
z = "global_search"
d = "diagnostics_picker"
D = "workspace_diagnostics_picker"

[keys.normal.g.c]
c = "toggle_comments"
d = "toggle_block_comments"

[keys.select]
right = "no_op"
left = "no_op"
down = "no_op"
up = "no_op"
"$" = "goto_line_end"
"0" = "goto_first_nonwhitespace"
"+" = "flip_selections"

[keys.select.g.c]
c = "toggle_comments"
d = "toggle_block_comments"
