[language-server.rust-analyzer.config]
check.command = "clippy"
diagnostics.enable = false
diagnostics.disabled = [ "inactive-code" ]
rustfmt.extraArgs = [ "+nightly" ]
cargo.features = "all"

[language-server.tailwindcss]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[language-server.steel-language-server]
command = "steel-language-server"
args = []

# [language-server.svelteserver]
# languages = { svelte = [{ formatCommand =  "prettierd --stdin-filepath ${INPUT}", formatStdin = true }]}

[[language]]
name = "git-commit"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "diff"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "rust"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "json"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "jsonc"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "typescript"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "typst"
formatter = { command = "typstyle", args = ["-t", "4", "--wrap-text", "-c", "70"] }
auto-format = true
indent = { tab-width = 4, unit = " " }

[[language]]
name = "svelte"
indent = { tab-width = 4, unit = "\t" }
language-servers = [ "svelteserver", "tailwindcss" ]
auto-format = true

[[language]]
name = "html"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "prettier", args = ["--parser", "html", "--use-tabs", "--stdin"] }
language-servers = ["vscode-html-language-server", "emmet-lsp"]
auto-format = true

[[language]]
name = "css"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "\t" }
# auto-format = true

[[language]]
name = "c"
indent = { tab-width = 4, unit = "\t" }
# auto-format = true

[[language]]
name = "cmake"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "toml"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "markdown"
indent = { tab-width = 4, unit = " " }

[[language]]
name = "java"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "scheme"
formatter = { command = "raco", args = ["fmt"] }
auto-format = true
language-servers = [ "steel-language-server" ]
